/*

 EXPLORE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 40
   Tile set      : E:\GB_D\cavesbg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define exploreWidth 64
#define exploreHeight 40
#define exploreBank 0

extern unsigned char explore[];

/* End of EXPLORE.H */
