/*

 COM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 23

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define com_spritesBank 0

/* Super Gameboy palette 0 */
#define com_spritesSGBPal0c0 6076
#define com_spritesSGBPal0c1 8935
#define com_spritesSGBPal0c2 6596
#define com_spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define com_spritesSGBPal1c0 6076
#define com_spritesSGBPal1c1 8935
#define com_spritesSGBPal1c2 6596
#define com_spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define com_spritesSGBPal2c0 6076
#define com_spritesSGBPal2c1 8935
#define com_spritesSGBPal2c2 6596
#define com_spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define com_spritesSGBPal3c0 6076
#define com_spritesSGBPal3c1 8935
#define com_spritesSGBPal3c2 6596
#define com_spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define com_spritesCGBPal0c0 6076
#define com_spritesCGBPal0c1 11585
#define com_spritesCGBPal0c2 598
#define com_spritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define com_spritesCGBPal1c0 6076
#define com_spritesCGBPal1c1 11585
#define com_spritesCGBPal1c2 6596
#define com_spritesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define com_spritesCGBPal2c0 6076
#define com_spritesCGBPal2c1 8935
#define com_spritesCGBPal2c2 6596
#define com_spritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define com_spritesCGBPal3c0 6076
#define com_spritesCGBPal3c1 8935
#define com_spritesCGBPal3c2 6596
#define com_spritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define com_spritesCGBPal4c0 6076
#define com_spritesCGBPal4c1 8935
#define com_spritesCGBPal4c2 6596
#define com_spritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define com_spritesCGBPal5c0 6076
#define com_spritesCGBPal5c1 8935
#define com_spritesCGBPal5c2 6596
#define com_spritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define com_spritesCGBPal6c0 6076
#define com_spritesCGBPal6c1 8935
#define com_spritesCGBPal6c2 6596
#define com_spritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define com_spritesCGBPal7c0 6076
#define com_spritesCGBPal7c1 8935
#define com_spritesCGBPal7c2 6596
#define com_spritesCGBPal7c3 5344

/* CGB palette entries. */
#define com_spritesCGB0 0
#define com_spritesCGB1 0
#define com_spritesCGB2 0
#define com_spritesCGB3 0
#define com_spritesCGB4 0
#define com_spritesCGB5 0
#define com_spritesCGB6 0
#define com_spritesCGB7 0
#define com_spritesCGB8 0
#define com_spritesCGB9 0
#define com_spritesCGB10 0
#define com_spritesCGB11 0
#define com_spritesCGB12 0
#define com_spritesCGB13 0
#define com_spritesCGB14 0
#define com_spritesCGB15 0
#define com_spritesCGB16 0
#define com_spritesCGB17 0
#define com_spritesCGB18 0
#define com_spritesCGB19 0
#define com_spritesCGB20 0
#define com_spritesCGB21 0
#define com_spritesCGB22 0
#define com_spritesCGB23 0
/* Start of tile array. */
extern unsigned char com_sprites[];

/* End of COM.H */
